cabal-version:      3.0
name:               haskaula
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Eu
maintainer:         nathanschiavetti@gmail.com
-- copyright:
category:           Web
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable haskaula
    import:           warnings
    main-is:          Main.hs
    other-modules:    Server.Handler
                      Types.Examples
    -- other-extensions:
    build-depends:    base,
                      servant,
                      servant-server,
                      wai,
                      wai-cors,
                      warp,
                      postgresql-simple,
                      aeson,
                      text
    hs-source-dirs:   app
    default-language: Haskell2010
